### PR TITLE
#18 Added a try catch to the resolving of group names

### PR DESCRIPTION
**Pull request by bzuidgeest**
Modifications as per issue #18

### CODE REVIEW

**Comment by sorengranfeldt** [comment]
Thank you. I'll include this in next release. Dont have a date set yet though. Time is a little scarse currently.

**Comment by bzuidgeest** [comment]
That is understandable I don't know where you live or if it is relevant, but in most countries things are a little strange right now. The main thing is you were open to the change, the rest will figure itself out.

**Comment by ngsmits** [comment]
Dear Sorengranfeldt,
Do you perhaps have any insight on a releasedate?

**Comment by sorengranfeldt** [comment]
I've not yet had time to look at this. I want to add a few extra things such as additional set credentials and may adding optional parameter list. Hopefully, I'll get around to looking at it before the end of March.

**Comment by sorengranfeldt** [comment]
Merged into latest version / release

**Pull request merged**
